### ISSUE TITLE
[Feature request] Trigger events for ip allocation

### ISSUE THREAD

**Issue by blackjid** [inlets/inlets-operator#10]
When running `kubectl get events -w` while adding a new loadbalancer, There is no log about the IP allocation for the service.

I can see an event when the service gets an IP from the dhcp through metallb. But nothing is registered for inlets operator.

```
# Example
kubectl get events -w
...
39s         Normal    IPAllocated         service/traefik                             Assigned IP "192.168.86.100"
39s         Normal    Synced              tunnel/nginx-tunnel                         Tunnel synced successfully
...
```

To reproduce

- Create a pod running nginx
- Espose nginx through a loadbalancer service
- Watch the events with `kubectl get events -w` until de service and the tunnel is created.

You'll see an `IPAllocated` event for the loadbalancer and a `Synced` event for the tunnel.

It would be nice to have an `IPAllocated` event for the load balancer with the new exit node and the tunnels are ready.

* inlets-operator version 0.2.6
* Kubernetes distribution k3s 0.8
* Kubernetes version `kubectl version`: v1.14.6-k3s.1

**Comment by alexellis** [comment]
Please give step by step instructions to reproduce this.

**Comment by blackjid** [comment]
I've updated the description

**Comment by alexellis** [comment]
Can you reproduce this without metallb? Ideally I don't want to complicate things and have three things giving out LB IPs.

**Comment by blackjid** [comment]
mm, I think you are right, it looks like metallb was triggering that event. 

Without metallb the `IPAllocated` event is not triggered. I thought that it might be a standard. 

Anyway seems reasonable to have an event from the loadbalancer saying that a new IP was allocated.

Feel free to close the issue if is not something you see worth adding.

**Comment by alexellis** [comment]
If you can find out how it works we can try to add it. Right now I'm updating the IP for the service so I'd expect to see the event.

**Comment by alexellis** [comment]
Can you see it here? https://github.com/danderson/metallb/blob/master/controller/main.go

**Comment by blackjid** [comment]
I think this is the line where the event is sent.
https://github.com/danderson/metallb/blob/master/controller/service.go#L115

I also checked on GKE and when a new loadbalancer is created, there is no event about the ip.

**Comment by alexellis** [comment]
What would you like to see happen with this issue @blackjid ?

**Comment by alexellis** [comment]
Closing as inactive
