### ISSUE TITLE
Digital Ocean Naive Install Spins Up multiple Droplets

### ISSUE THREAD

**Issue by Spazzy757** [inlets/inlets-operator#100]
Doing a simple install of the inlets operator and I then installed an ingress on my cluster which started multiple hosts on my Digitial Ocean Account (there was only a single service with `type=LoadBalancer`)

## Expected Behaviour
A single DO droplet gets started and I then have an IP address for my Kind cluster, when I delete the Service it should delete the corresponding Droplet.

## Current Behaviour
It seems to get stuck and spins up a new Droplet on each reconciliation:
![image](https://user-images.githubusercontent.com/19777480/94931397-02b02280-04c8-11eb-9d2c-e906affeebe4.png)

Then when I delete the Helm Chart, the Droplets remain.

## Steps to Reproduce (for bugs)

```bash
kind create cluster --name test

 kubectl create secret generic inlets-access-key \
            --from-literal inlets-access-key=$DO_TOKEN

kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/0.9.0/artifacts/crds/inlets.inlets.dev_tunnels.yaml
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/0.9.0/artifacts/operator-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/0.9.0/artifacts/operator.yaml

helm install ingress ingress-nginx/ingress-nginx
```

## Context
I really love this idea, I've been looking for something like this. In all honesty, I have not touched any of the default settings or configurations as of yet. I just worry that a naive installer that installs this might spin up many Droplets without realising and this could cause them to break DO fair usage policy and have their account blocked (I have had this happen before).

Let me know if I can help out. I'd love to contribute

## Your Environment

- inlets-operator version: `0.7.4`
- kind version: `v0.9.0 go1.15.2 darwin/amd64`
- kubernetes: `v1.19.1`
- operating System: `MacOs`
- Cloud Provisioner: `Digitial Ocean`

**Comment by Spazzy757** [comment]
For more insight, the logs of the operator:
```logs
inlets-operator-69f959bb48-phtjj operator I1002 13:53:03.613276       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-admission'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:03 Creating tunnel for ingress-ingress-nginx-controller-tunnel.default
inlets-operator-69f959bb48-phtjj operator I1002 13:53:03.698237       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:03 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:04 Provisioning call took: 0.975843s
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:04 Status (ingress-ingress-nginx-controller): provisioning, ID: 210308755, IP:
inlets-operator-69f959bb48-phtjj operator I1002 13:53:04.687152       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-tunnel'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:04 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:05 Provisioning call took: 0.965609s
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:05 Status (ingress-ingress-nginx-controller): provisioning, ID: 210308756, IP:
inlets-operator-69f959bb48-phtjj operator I1002 13:53:05.639543       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-tunnel'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:05 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:06 Provisioning call took: 0.735494s
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:06 Status (ingress-ingress-nginx-controller): provisioning, ID: 210308758, IP:
inlets-operator-69f959bb48-phtjj operator I1002 13:53:06.393555       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-tunnel'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:06 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:07 Provisioning call took: 0.853589s
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:07 Status (ingress-ingress-nginx-controller): provisioning, ID: 210308760, IP:
inlets-operator-69f959bb48-phtjj operator I1002 13:53:07.262236       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-tunnel'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:07 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:07 Provisioning call took: 0.631211s
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:07 Status (ingress-ingress-nginx-controller): provisioning, ID: 210308762, IP:
inlets-operator-69f959bb48-phtjj operator I1002 13:53:07.908458       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-tunnel'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:24 Provisioning host with DigitalOcean
inlets-operator-69f959bb48-phtjj operator I1002 13:53:24.579993       1 controller.go:310] Successfully synced 'default/ingress-ingress-nginx-controller-admission'
inlets-operator-69f959bb48-phtjj operator 2020/10/02 13:53:24 Tunnel exists: ingress-ingress-nginx-controller-tunnel
```

**Comment by alexellis** [comment]
Hi @Spazzy757 sorry to hear you are having difficulties.

I did create a patch for a similar issue to this several months ago, and it seems that you're using a very old version.

Can I ask why you are using such an old version 0.7.4 is shown in your screenshot? My suggestion would be to update to 0.9.1

For deleting your additional droplets I'd suggest using `doctl compute droplet ls` and `doctl compute droplet rm --force ID`

You can download doctl using [Arkade](https://get-arkade.dev) `arkade get doctl`

Alex

<img width="331" alt="Screenshot 2020-10-02 at 15 17 06" src="https://user-images.githubusercontent.com/6358735/94933496-5b7cbc80-04c2-11eb-991f-072d10b9a828.png">

**Comment by Spazzy757** [comment]
Fantastic! Apologies, I will try it right now!

**Comment by Spazzy757** [comment]
works perfectly thank you!

**Comment by alexellis** [comment]
I can see that you're using `kubectl apply` and static YAML files. I've now completely removed that option, so that users are pointed at helm or arkade (recommended, as it automates the helm chart options)

This should put you on a newer version, let me know if we need to re-open the PR. I'd suggest deleting your kind cluster in the meantime, and looking at one of the tutorials for Kubernetes such as: https://docs.inlets.dev/#/get-started/quickstart-ingresscontroller-cert-manager?id=expose-your-ingresscontroller-and-get-tls-from-letsencrypt

**Comment by Spazzy757** [comment]
Okay, perfect thank you! I'm generally a fan of using static yaml as most of my local automation is around kustomize but I will just template out the helm chart so no stress to reopen! Thanks again for the crazy quick reply and solve! Have a good weekend

**Comment by alexellis** [comment]
If you become a GitHub sponsor then you can receive regular updates on this project, and on Kubernetes. Checkout my personal profile for the details. 

Do check out the PRO edition which is more secure and useful with the out of the box configuration. https://inlets.dev
