### ISSUE TITLE
[Restated] Support request for multiple LoadBalancer controllers

### ISSUE THREAD

**Issue by DarkBlaez** [inlets/inlets-operator#101]
Alex

This question was posed prior, you referenced a document which most of us are aware of and then closed the issue. Here it is restated

Is it possible to extend the annocations to bypass inlets as the LoadBalancer, flipping this around to create an annocation that inlets-operator looks for to explicitly deploy. Like many, MetalLB is the default bare metal loadbalancer in a cluster for certain situations. Deploying the inlets-operator would result in two LB competing. MetalLB will always attempt to service type LoadBalancer.

The inlets-operator is the ideal solution for routing external traffic in to a private cluster without having to go the route of site-to-site vpn and routing traffice. However, as I suspect inlets will interrogate all service types LB and go back and open up VMs for each.

Use case trying to be solved. IP addresses being assigned to internal services/sites, API gateway trying to be exposed to external internet traffic, inlets is ideal for this, whereas MetalLB is ideal fo assignin IP for internal use (private net)

DB

My commentary to your docs you posted, this still creates a situation when another LB is competing with Inlets Operator. The default behavior for Inlets Operator should be to check for an annotation and then be activated. Not the converse which is active unless annotated otherwise. Inlets was not meant to be a LB. The abundance of mainstream LB soft-options exist and are in use. Your recommended approach essentially would cause going back an annotating every instance of a LB service and redeployment of a manifest. The use case for Inlets Operator is for selective deployment and function, not overarching LB instancing. I cannot think of one use case where someone who grants LB IP assignment to say even 20 services (can be anything from DB, Queue, etc) would want Inlets instantiating a remove VM for each. Inlets Operator has a very specific use case.

**Comment by alexellis** [comment]
Help me understand what I'm missing? I answered this on the previous issue that was closed as resolved.

I'd rather keep all the conversation in place, so please can you close this as a duplicate and post your comment there? #95

**Comment by alexellis** [comment]
Duplicate issue of #95

**Comment by alexellis** [comment]
> My commentary to your docs you posted, this still creates a situation when another LB is competing with Inlets Operator. The default behavior for Inlets Operator should be to check for an annotation and then be activated.

That's what the annotation does. There are two modes for it, I linked you to both of those in two separate comments before you went ahead and opened another duplicate issue. I'm sorry if you feel frustrated, but one issue is enough for discussion, and even if it's closed, you can keep on commenting.

<img width="889" alt="Screenshot 2020-10-16 at 20 17 19" src="https://user-images.githubusercontent.com/6358735/96299875-9e737f80-0fec-11eb-8d9b-dd23a2f894cf.png">

<img width="939" alt="Screenshot 2020-10-16 at 20 17 10" src="https://user-images.githubusercontent.com/6358735/96299886-a03d4300-0fec-11eb-93b2-aaa46c7b6d2a.png">

Feel free to test it out and comment back with a series of steps that show a scenario where it doesn't do what you expected, I'll re-open this issue or the other one.

**Comment by alexellis** [comment]
Just one more thing, I would suggest that you consider using inlets PRO with the operator so that you can benefit from encryption for the control-plane of your inlets tunnels.
