### ISSUE TITLE
running inlets operator with without cloud

### ISSUE THREAD

**Issue by xsteadfastx** [inlets/inlets-operator#109]
i run a inlets server on a bare metal server as normal systemd service. i use it mostly as an open source ngrok alternative to share some stuff from my laptop. now im doing more and more with kubernetes and would love to use this public bare metal inlets server with kubernetes. is this possible at all? or does inlets-operator needs to create a cloud instance by itself?

thanks for this beautiful piece of software... im using it alot :)

**Comment by alexellis** [comment]
Yes that's supported, you should take a look at our helm chart for inlets PRO, it's not free, but it is easy to use any you've already seen the value of Inlets so I'd suggest you try it.

https://github.com/inlets/inlets-pro/tree/master/chart/inlets-pro

**Comment by alexellis** [comment]
Happy to customise the chart for Inlets PRO to support your usecase of exposing the services tunneled in. By default it keeps them private to act like a VPN.

**Comment by xsteadfastx** [comment]
thank you alot :) for this wonderful piece of software and your changes!

**Comment by alexellis** [comment]
The chart is for inlets PRO, but I am not sure if you're a customer. Would you like to take out a free trial?

**Comment by xsteadfastx** [comment]
yeah why not :-)

right now im using inlets alot for web development stuff... like a free ngrok alternative only.

**Comment by alexellis** [comment]
https://inlets.dev/
