### ISSUE TITLE
The loadbalancer external ip is not cleared when the tunnel is removed

### ISSUE THREAD

**Issue by blackjid** [inlets/inlets-operator#11]
If I manually remove the tunnel object associated to a loadbalancer, the garbage collector does not clear the external ip of the service. This make the loadbalancer service state inconsistent.

I already have a working fix so I could open a PR with it.

## Expected Behaviour
I would expect the node-exit ip to be removed from the externalips on the loadbalancer service.

## Steps to Reproduce 
1. Create a new loadblancer service
```	
kubectl run nginx-1 --image=nginx --port=80 --restart=Always
kubectl expose deployment nginx-1 --port=80 --type=LoadBalancer
```

This will make the inlets operator to create a new tunnel and update the service with the exit node ip.

2. Annotate de loadbalaner with `dev.inlets.manage=false`

This is where I think this is an edge case. This is because I will manually remove the tunnel and I don't want the operator to recreated it.

3. Remove the tunnel associated with the loadbalancer

```
kubectl delete tunnels nginx-1-tunnel
```

4. Get the service an check the external ip is still there.

```
kubectl get services
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                  AGE
nginx-1          LoadBalancer   10.43.62.113   167.99.94.58   80:31447/TCP             25h
...
```

The service still have the node-exit IP associated in the external ip section

## Context
This is somehow an edge case. But I think one is worth fixing given the inconsistent state the loadbalancer has after the tunnel is removed

**Comment by alexellis** [comment]
Hi @blackjid I've updated the title with what I think you wanted to say.

Let me know if you'd be interested in working on this?

Alex

**Comment by blackjid** [comment]
Sorry if I wasn't clear. I also thought about what you described, that the operator remove the tunnel when the loadbalancer annotation changes to false. But I was thinking of something else. 

I'll update the description trying to be more specific.

**Comment by blackjid** [comment]
I've updated the title back to what I really meant.
I've opened a PR fixing this also.

I'll open an issue with what you thought I was talking about.
