### ISSUE TITLE
Add new Hetnzer provisioner to operator

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#115]
There is a working [Hetnzer provisioner](https://github.com/inlets/cloud-provision/blob/master/provision/hetzner.go) which we can add to the operator now.

## Expected Behaviour

Users on Hetzner should be able to use the inlets-operator

## Current Behaviour

It's not yet available

## Possible Solution

Adding it to the controller should be a case of:

1) Find all references of "EC2" or "DigitalOcean"
2) Copy/paste
3) Test end to end with exposing a service, accessing it and then deleting the service to check the VM is removed.

Finally, update the [arkade app](https://github.com/alexellis/arkade/blob/master/cmd/apps/inletsoperator_app.go) to take the new flag via `--provider`

Requested in #44

**Comment by alexellis** [comment]
@felipecruz91 didn't have time to finish the PR, so if anyone lands here and wants to work on this, feel free.

Thanks

**Comment by alexellis** [comment]
/add title: good first issue, help wanted

**Comment by kyeett** [comment]
I can give this a try, if you want.
