### ISSUE TITLE
Change to inlets-pro

### ISSUE THREAD

**Issue by bnason** [inlets/inlets-operator#117]
It looks like this was changed to use the pro version which requires purchasing a license (or getting a temporary free one). Is there no longer any way to use the non pro version?

## Expected Behaviour
To be able to use the OSS version as described in the README.md.
It makes it sound like you have to provide a license to "upgrade" to the pro version, but now that seems like a requirement.

## Current Behaviour
When installing via helm chart, after the DO vm gets created, the pod fails because it's trying to execute inlets-pro

## Possible Solution
Provide options to select non pro version

**Comment by alexellis** [comment]
Happy to offer you a discount if you were using this at work?

For personal users inlets PRO is already discounted, and sponsors get a further 10% discount for personal licenses.

The primary reason we made this change was written up on Slack and sent to all GitHub Sponsors

<img width="386" alt="Screenshot 2021-01-26 at 12 36 08" src="https://user-images.githubusercontent.com/6358735/105845680-14678980-5fd3-11eb-8274-16528ac6cb33.png">

<img width="953" alt="Screenshot 2021-01-26 at 12 36 36" src="https://user-images.githubusercontent.com/6358735/105845734-277a5980-5fd3-11eb-945e-e105ac6ff94e.png">

Ultimately, inlets OSS is still free and open source and unchanged from before.

inlets-operator and inletsctl are now secure by default.

**Comment by alexellis** [comment]
Hope this was helpful to you.

We have just announced personal use licenses can be used at work. 

Inlets and openfaas sponsors can also get 10% off through the Treasure Trove portal.

https://twitter.com/alexellisuk/status/1354127661875003398?s=19
