### ISSUE TITLE
tunnel-client pod won't start, "exec: "inlets-pro": executable file not found in $PATH"

### ISSUE THREAD

**Issue by Igglybuff** [inlets/inlets-operator#118]
## Expected Behaviour
The inlets tunnel pod starts up successfully so I can reach the LoadBalancer service.

## Current Behaviour
The traefik-tunnel-client pod fails to start with the following event (nothing in the pod logs):

```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "inlets-pro": executable file not found in $PATH: unknown
```

## Steps to Reproduce (for bugs)
Deployed Traefik (default bundled with k3s) which has a LoadBalancer service:

```
$ kubectl get svc -n kube-system traefik
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP                 PORT(S)                      AGE
traefik   LoadBalancer   10.43.26.203   178.x.x.x,178.x.x.x   80:32661/TCP,443:30778/TCP   36m
```
(public IP is hidden just in case...)

A droplet is created in DO and the LB gets its correct external IP.
![image](https://user-images.githubusercontent.com/8899226/107866567-27e77100-6e6a-11eb-816c-88a8430732d3.png)

```
$ kubectl get po -n kube-system
NAME                                     READY   STATUS             RESTARTS   AGE
local-path-provisioner-7ff9579c6-kh75s   1/1     Running            0          39m
metrics-server-7b4f8b595-ltpws           1/1     Running            0          39m
coredns-66c464876b-8dft5                 1/1     Running            0          39m
helm-install-traefik-2rkqw               0/1     Completed          0          6m27s
traefik-5bf464fc54-7x24s                 1/1     Running            0          6m18s
traefik-tunnel-client-564cfb6495-zk2xq   0/1     CrashLoopBackOff   8          20m
```
The tunnel pod doesn't start, no logs, just this event:
```
$ kubectl get events -n kube-system | grep inlet
21m         Normal    Pulling             pod/traefik-tunnel-client-564cfb6495-zk2xq    Pulling image "inlets/inlets:2.7.10"
21m         Normal    Pulled              pod/traefik-tunnel-client-564cfb6495-zk2xq    Successfully pulled image "inlets/inlets:2.7.10" in 11.271171684s
19m         Normal    Pulled              pod/traefik-tunnel-client-564cfb6495-zk2xq    Container image "inlets/inlets:2.7.10" already present on machine
19m         Warning   Failed              pod/traefik-tunnel-client-564cfb6495-zk2xq    Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "inlets-pro": executable file not found in $PATH: unknown
```

## Context
Just trying to set up inlets with Traefik for public ingress to my cluster.

## Your Environment
> inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`

Deployed via Helm, chart version 0.12.0. I don't override any of the default values.

```
$ kubectl get deploy inlets-operator -n inlets -o wide
NAME              READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS        IMAGES                                  SELECTOR
inlets-operator   1/1     1            1           29m   inlets-operator   ghcr.io/inlets/inlets-operator:0.12.0   app.kubernetes.io/instance=inlets-operator,app.kubernetes.io/name=inlets-operator
```

> Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:

k3s

> Kubernetes version `kubectl version`:

v1.19.7+k3s1

> Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Linux k3s0 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
```

This is a Raspberry Pi cluster made of four Raspberry Pi 4 B 8GB, one Raspberry Pi 3 B, and one Raspberry Pi 2.

**Comment by Igglybuff** [comment]
Looks like this now needs a pro license to be useful at all - I guess it's no longer an option for hobbyists trying to keep things FOSS 🤷‍♂️

**Comment by alexellis** [comment]
Hi,

Please see https://github.com/inlets/inlets-operator/issues/117 particularly the notes.

You're still welcome to use the inlets-operator, which itself is still licensed MIT. If you find this tool useful then you can support the project and community by purchasing a personal license.

Alternatively, inlets itself has not gone away and you can set it up manually it you have the time to spend doing that.

Thank you,

Alex

**Comment by Igglybuff** [comment]
That's fine, but this could be made more obvious in the README. I imagine most people come across this on GitHub and assume it's an out-of-the-box solution to getting public LoadBalancer services in Kubernetes, but there is in fact a wall to a) purchase a license or b) somehow figure out how to set it up manually. Instead it just says "powered by inlets PRO" and it only becomes abundantly clear that you have to pay when you go to the pricing page on the inlets website.

**Comment by alexellis** [comment]
Thanks for your feedback. I would recommend checking out the docs for the operator

https://docs.inlets.dev/#/tools/inlets-operator?id=inlets-operator-reference-documentation

As I said on the linked issue, there's a heavily discounted licence for personal use that can also be used at work for commercial purposes. Sponsors of inlets or openfaas get an additional 15% off that again.

Thank you for your interest this project. If you find it useful and if it saves you time, consider supporting it. Otherwise there's ways you can configure it manually (using your own time instead) for "free"
