### ISSUE TITLE
Proposal: Add Scaleway provider

### ISSUE THREAD

**Issue by alexandrevilain** [inlets/inlets-operator#12]
Scaleway is a great and cheap provider. I think that this provider is well suited for this operator.

## Expected Behaviour
Adding the `--provider scaleway` flag should provision a new scaleway instance.  

## Current Behaviour
We can't provision a scaleway instance.

## Possible Solution
1. Add `scaleway.go` file to the `pkg/provision` package
2. Add scaleway in the controller.

Their new SDK seems to be pretty easy to use: https://github.com/scaleway/scaleway-sdk-go 
I think that the controller part should be refactored to stay readable even if we add new providers.

I can do the pull request if you approve this proposal 😃 

## Context
I'm always using scaleway for all my tests: it's fast and cheap!

**Comment by alexandrevilain** [comment]
Hi @alexellis 
I just saw that you added scaleway on your todo list 😁 ! 
I was waiting for your approval, but I started to develop it as it's on the road map now :)

**Comment by alexellis** [comment]
> I think that the controller part should be refactored to stay readable even if we add new providers.

There's an interface for adding provisioners, but the controller still has some provider-specific code in it, which could be improved after adding Scaleway.

Please feel free to work on the PR 👍

**Comment by alexandrevilain** [comment]
Yes, I will first create the PR for Scaleway :) 

Then I'll do another to refacto the provider-specific code in the controller!
