### ISSUE TITLE
Update OS images to Ubuntu 18.04 for provisioners

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#124]
Update OS images to Ubuntu 18.04 for provisioners

## Expected Behaviour

OS images need to be bumped to 18.04 and re-tested for each cloud provisioner

## Current Behaviour

We have a mix of 16.04 and 18.04, as we saw in: https://github.com/inlets/inletsctl/issues/95, some providers are removing their images given that the release lost support in April 2021.

## Possible Solution

Find new "code" or "slug" for the Ubuntu 18.04 image.

Update the code, rebuild, deploy, test creation, verify the OS image is as launched expected in the provider's dashboard.

## Context

Some images are being removed, but all of them are now out of support, so could become subject to vulnerabilities that do not receive a subsequent fix.

**Comment by dirien** [comment]
So whats left?

**Comment by alexellis** [comment]
Good question @dirien, please can you take a look and report back?

Also, do you want to add back Civo, now that their API seems to resolve IPs correctly during cloud-init?

**Comment by dirien** [comment]
I wanted to talk to you in the community call. We need to change the cloud provision to what you did for GCE. 


As Civo  needs, again wrong in their docs, the Region when asking for the Status
```bash
https://www.civo.com/api/instances#list-instances

curl -H "Authorization: bearer xxx" https://api.civo.com/v2/instances/5720506e-e523-484a-8916-e9311e4ea602
{"code":"database_instance_find","result":"not found","reason":"Failed to find the instance in the internal database"}% 
```

vs
```bash
 curl -H "Authorization: bearer xx" "https://api.civo.com/v2/instances/5720506e-e523-484a-8916-e9311e4ea602?region=LON1"
{"id":"5720506e-e523-484a-8916-e9311e4ea602","name":"nginx-1-tunnel-2da04aa5","hostname":"nginx-1-tunnel",..snip..,"cpu_cores":1,"ram_mb":1024,"disk_gb":25}%
```

I created a ticket at civo (https://github.com/civo/civogo/issues/55), that list instances should give all instances over all regions. They want to overall change their API, but for now they dont want to fix it.

 Or we need to go the GCE way of encoding infos in the instance id and split them again

**Comment by alexellis** [comment]
Thanks, can you create a separate ticket here or in the inlets/cloud-provision reop to track the problem?

Do we have any provisioners which still need updating to Ubuntu 18.04, or can we close this issue now?

**Comment by dirien** [comment]
IN inlets-operator all are updated.

in inletsctl: 
https://github.com/inlets/inletsctl/blob/ed0bcc767eb9357bef75062dee746684b97eb0bf/cmd/create.go#L428

https://github.com/inlets/inletsctl/blob/ed0bcc767eb9357bef75062dee746684b97eb0bf/cmd/create.go#L489

**Comment by alexellis** [comment]
And are we good with inletsctl now also?

**Comment by dirien** [comment]
inletsctl has ec2 and equinix still open, see links above

**Comment by dirien** [comment]
@alexellis: i think that issue can be closed.

**Comment by alexellis** [comment]
Thank you
