### ISSUE TITLE
Update provider pricing grid

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#135]
The provider pricing grid needs updating with the newest options and costs.

## Expected Behaviour

The provider grid needs to be kept up to date with the various provisioners that we support and how much they cost roughly per month.

## Current Behaviour

It's a bit out of date

## Possible Solution

Update it at: https://github.com/inlets/inlets-operator#provider-pricing

Then I would suggest moving it into the inlets docs website at https://github.com/inlets/docs because it will be used for inletsctl too and is common information.

We can also mention what free tier clouds exist there.

**Comment by alexellis** [comment]
@dirien could you help?

cc @jsiebens

**Comment by dirien** [comment]
@alexellis , yes can do
