### ISSUE TITLE
Format Error: JWT Token for license-file 

### ISSUE THREAD

**Issue by joshua-hester** [inlets/inlets-operator#137]
I am receiving an error when using my  LICENSE String for Inlets Pro

Format: XXXXX-XXXXX-XXXXX-XXXXX etc. 

What is the format for the License File?

Command: 
```
arkade install inlets-operator \
 --provider digitalocean \
 --region nyc1 \
 --token-file $HOME/do-access-token --license-file $HOME/LICENSE.txt
```

When running ` kubectl logs -n default deploy/inlets-operator` I receive the following

```
2021/07/31 16:54:40 Operator version: 0.14.0 SHA: 1b3e8332706594324b22e8d994b32a5cdc8c6279
2021/07/31 16:54:40 Client image: ghcr.io/inlets/inlets-pro:0.8.8
inlets PRO license may be invalid
```

I know the license is valid because I ran Inlets-Pro locally and was able to set up a valid connection.

My Question: What is the JWT token format for this to work correctly?

**Comment by joshua-hester** [comment]
I am almost positive its a small formatting error because its receiving this error because of line	
https://github.com/inlets/inlets-operator/blob/7ce7ac3e402743e1e2700a9b4baa68358a4756a8/config.go#L53

it is definitely looking for two "period" characters that I do not have in the License string

**Comment by alexellis** [comment]
Hi there, sorry about this. It's a piece of validation that needs to be removed for the Gumroad tokens.

I'll get a patched version up for you this weekend and close you'd issue when it's ready. 

Alex

**Comment by alexellis** [comment]
Here's the fix: https://github.com/inlets/inlets-operator/releases/tag/0.14.1

You'll be able to install again and the chart will update to this version.

**Comment by joshua-hester** [comment]
@alexellis Thank you! Very speedy! Just reinstalled and it worked perfect ...
