### ISSUE TITLE
Getting 401 Unable to Authenticate from Digital Ocean

### ISSUE THREAD

**Issue by sammydev395** [inlets/inlets-operator#139]
I had to reinstall the inlets operator on my Mac Mini running KinD and am now getting auth issues as u see below, even though the pod is up and running fine with Inlets pro operator

I have tried using a fresh new generated token from Digital Ocean when installing the inlets operator on Kind via arkade

## Expected Behaviour
Digital Ocean droplet should be created

## Current Behaviour
`2021/08/16 17:38:22 Provisioning started with provider: digitalocean host: gateway-proxy-tunnel
2021/08/16 17:38:22 Provisioning host with DigitalOcean
E0816 17:38:22.940919       1 controller.go:326] error syncing 'gloo-system/gateway-proxy-tunnel': POST https://api.digitalocean.com/v2/droplets: 401 Unable to authenticate you, requeuing
2021/08/16 17:38:22 Provisioning started with provider: digitalocean host: gateway-proxy-tunnel
2021/08/16 17:38:22 Provisioning host with DigitalOcean
E0816 17:38:23.184374       1 controller.go:326] error syncing 'gloo-system/gateway-proxy-tunnel': POST https://api.digitalocean.com/v2/droplets: 401 Unable to authenticate you, requeuing
2021/08/16 17:38:23 Provisioning started with provider: digitalocean host: gateway-proxy-tunnel
2021/08/16 17:38:23 Provisioning host with DigitalOcean
E0816 17:38:23.508714       1 controller.go:326] error syncing 'gloo-system/gateway-proxy-tunnel': POST https://api.digitalocean.com/v2/droplets: 401 Unable to authenticate you, requeuing
2021/08/16 17:38:24 Provisioning started with provider: digitalocean host: gateway-proxy-tunnel
2021/08/16 17:38:24 Provisioning host with DigitalOcean
E0816 17:38:25.039741       1 controller.go:326] error syncing 'gloo-system/gateway-proxy-tunnel': POST https://api.digitalocean.com/v2/droplets: 401 Unable to authenticate you, requeuing`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
inlets-operator   1/1     1            1           17m   inlets-operator   ghcr.io/inlets/inlets-operator:0.14.1   app.kubernetes.io/instance=inlets-operator,app.kubernetes.io/name=inlets-operator

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
KinD

* Kubernetes version `kubectl version`:
1.21.1

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Cloud provisioner:

**Comment by alexellis** [comment]
Hi @sammydev395 it sounds like you have a problem with your token.

I would suggest removing the secret created by arkade and installing the app again.

For further technical assistance, feel free to use the community Slack. Commercial customers with business licenses have support via email included for free.

Alex

**Comment by alexellis** [comment]
The secret created by the operator is called "inlets-access-key"
