### ISSUE TITLE
question: is the inletsProLicense field of the helm chart different than the lic key received in email

### ISSUE THREAD

**Issue by LordNoteworthy** [inlets/inlets-operator#153]
Hello,

I have recently purchased a inlets personal license, and i have received a key in email in the form of XXXXX-XXXXX-XXXXX-XXXXX.

In the doc, it says something about JWT license ? Is it the same or is it something else ? If then, how to obtain the JWT token.

I am saying this because the tunnel pod of ingress says something like:

```
{"success":false,"message":"That license does not exist for the provided product."}
Error: error with subscription: invalid Gumroad subscription: 404
```

**Comment by alexellis** [comment]
Hi, could you fill out the whole issue template and I'll try to assist. 

Alex

**Comment by LordNoteworthy** [comment]
Hello @alexellis 

inlet-operator license does not seems to be accepted.

## Expected Behaviour
When I create my ingress, a ingress-nginx-controller-tunnel-client pod get created but it is failing.

```
jupiter-ingress-nginx-controller-797f9874f8-fxbfr                 1/1     Running            9 (92m ago)       23h
jupiter-ingress-nginx-controller-tunnel-client-6ff68bb8bd-p4nhs   0/1     CrashLoopBackOff   296 (4m24s ago)   22h
```

## Current Behaviour
Here is the log that comes out of the failing pod:

```sh
> kl jupiter-ingress-nginx-controller-tunnel-client-6ff68bb8bd-p4nhs
Starting TCP client. Version: 0.9.1 - 99e1785a9599ba43e149edc748c47319a325f9c9
{"success":false,"message":"That license does not exist for the provided product."}
Error: error with subscription: invalid Gumroad subscription: 404
```

## Steps to Reproduce (for bugs)

```sh
kubectl apply -f  https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/crds/inlets.inlets.dev_tunnels.yaml
helm repo add inlets https://inlets.github.io/inlets-operator/
```

My Chart.yaml has the following dependency:
```yaml
- name: inlets-operator
  version: 0.16.0
  repository: https://inlets.github.io/inlets-operator/
  condition: inlets-operator.enabled
```

- Then: `helm dependency update`
-  kubectl create secret generic inlets-access-key --from-file=inlets-access-key=inlets-access-key
-  kubectl create secret generic inlets-secret-key --from-file=inlets-secret-key=inlets-secret-key

my values.yaml:
```yaml
inlets-operator:
  enabled: true
  provider: ec2
  region: us-east-1
  secretKeyFile: /var/secrets/inlets/secret/inlets-secret-key
  inletsProLicense: "XXXXX-XXXXX-XXXXX-XXXXX"
```


## Context
Once I try to upgrade my helm release, I can see that the operator looks fine, and the EC2 instance get created successfully and I have obtained a public IP for my ingress object but the tunnel pod is failing.


## Your Environment

```sh
❯ kubectl get deploy jupiter-inlets-operator -o wide 
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS        IMAGES                                  SELECTOR
jupiter-inlets-operator   1/1     1            1           23h   inlets-operator   ghcr.io/inlets/inlets-operator:0.15.0   app.kubernetes.io/instance=jupiter,app.kubernetes.io/name=inlets-operator
```

- Operating System and version: Debian 11.
- Kubernetes distribution: Kubespray deployed in Bare Metal.
- Kubernetes version: 
```sh
❯ k get nodes -o wide        
node1   Ready    <none>                 28h   v1.23.6   192.168.1.7   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-14-amd64   containerd://1.6.4
node2   Ready    <none>                 28h   v1.23.6   192.168.1.8   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-14-amd64   containerd://1.6.4
node3   Ready    control-plane,master   28h   v1.23.6   192.168.1.9   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-14-amd64   containerd://1.6.4
```

Cheers.

**Comment by alexellis** [comment]
Thanks for adding that information.

I am wondering if there is an issue with your specific Gumroad key.

Can you try to run the inlets-pro client on your local machine with your license key from Gumroad and see if it works?

Gumroad subscriptions use their own format of keys, static purchases use a JWT.

**Comment by alexellis** [comment]
I've just run through the above with a license key from Gumroad, the exit servers were created as expected.

```bash
#!/bin/bash

kubectl apply -f \
  https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/crds/inlets.inlets.dev_tunnels.yaml

kubectl create secret generic inlets-access-key \
  --from-file=inlets-access-key=$HOME/do-access

helm repo add inlets https://inlets.github.io/inlets-operator/

helm repo update


helm upgrade inlets-operator --install inlets/inlets-operator \
  -f inlets-values.yaml
```

And values:

```yaml
provider: digitalocean
region: lon1
inletsProLicense: AAAAAAAA-BBBBBBBB-CCCCCCCC-DDDDDDDD
```

I'll await the confirmations on the three questions above.

**Comment by LordNoteworthy** [comment]
Hello  @alexellis 

I have just send an email containing the information you need, and I confirm I did not cancel my license.

Thank you so much.

**Comment by alexellis** [comment]
Turns out this was down to the license not being copied correctly from the email, which we resolved over email. I'll close this but feel free to open other issues if you run into different problems.
