### ISSUE TITLE
digitalocean image ubuntu-18-04-x64 is no longer available

### ISSUE THREAD

**Issue by dleidisch** [inlets/inlets-operator#166]
## Expected Behaviour
The operator should create a new droplet at DigitalOcean.

## Current Behaviour
The inlets-operator attempts to create a new droplet at DigitalOcean, but the image (ubuntu-18-04-x64) is no longer available, and DigitalOceanrejects the droplet createion with the error message "`You specified an invalid image for Droplet creation., requeuing.`"

## Possible Solution

The creation should at least use Ubuntu 20-04-x64 (LTS) - ubuntu-20-04-x64

`OS:         "ubuntu-20-04-x64",`

https://github.com/inlets/inlets-operator/blob/master/controller.go#L773

## Your Environment

* inlets-operator version: ghcr.io/inlets/inlets-operator:0.17.5
* Cloud provisioner: digitalocean

**Comment by alexellis** [comment]
Hi @dleidisch 

I'd be happy to take a look into this for you.

Are you interested in contributing the fix?

Regards,

Alex

**Comment by alexellis** [comment]
Actually, this is something I can take and test quite quickly, here's the fix:

https://github.com/inlets/inlets-operator/commit/7201a004bb5d247d04f3cd66cb7b764db55a7d52

Expect a new release shortly.

Thanks again for being a loyal customer.

**Comment by dleidisch** [comment]
Thank you for the fast help!

**Comment by alexellis** [comment]
![inlets-patch](https://github.com/inlets/inlets-operator/assets/6358735/8828c23e-0681-4e76-af65-454314f22286)

No worries, here is a sample of running it locally. Let us know if your issue is resolved with the latest release I just published.

**Comment by dleidisch** [comment]
Thanks! The creation process is working again.
