### ISSUE TITLE
Is there any option of open source for inlets? If it exists, how to use it? I cant find anywhere in documentation how to use inlets free version.

### ISSUE THREAD

**Issue by GabSnow24** [inlets/inlets-operator#167]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:

* Kubernetes version `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Cloud provisioner:

**Comment by alexellis** [comment]
No, inlets itself is a product not free software. 

The cost for personal use is 20 USD per month, so that’s your best option. 

If you can’t pay for the subscription then it’s not right for you.
