### ISSUE TITLE
[Feature] Add provisioner for AWS EC2

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#18]
## Expected Behaviour

[Feature] Add provisioner for AWS EC2

## Current Behaviour

Exit nodes can be provisioned to DO/Packet

## Possible Solution

1) Explore the "provision" package - https://github.com/inlets/inlets-operator/tree/master/pkg/provision

2) Integrate the AWS SDK for Go

Example: https://docs.aws.amazon.com/code-samples/latest/catalog/go-ec2-create_instance.go.html

**Comment by alexandrevilain** [comment]
Hi @adamjohnson01 are you still working on it ? I'll be happy to help

**Comment by adamjohnson01** [comment]
@alexandrevilain, I have not had time to start yet so feel free to go ahead.

**Comment by alexellis** [comment]
This code has moved to inletsctl, so a PR is needed there first, a release and then vendor-ing back into this project to complete the workflow.

I don't mind who works on this. IMHO it's up for grabs until a working PR is submitted.

**Comment by alexandrevilain** [comment]
Hi @alexellis ! Yes, I saw this change yesterday. No problem I'll do the PR on inletctl.

**Comment by alexellis** [comment]
Related: https://github.com/inlets/inletsctl/issues/15

Folks given the inactivity since this was raised on October 18th, I'm looking for someone to do the work and submit a PR, just claiming the issue and not sending a PR isn't enough and probably puts other people off.

**Comment by alexandrevilain** [comment]
Sorry @alexellis, Chrismas Holidays don't help to find time to work on it !

**Comment by alexandrevilain** [comment]
Hi @alexellis @adamjohnson01 

I was creating my PR when I saw this one: https://github.com/inlets/inletsctl/pull/16.

I don't understand, you said that you didn't have time.

So if you want it, here is my contribution: https://github.com/alexandrevilain/inletsctl/tree/add-aws

**Comment by adamjohnson01** [comment]
@alexandrevilain, I saw the post by Alex and felt guilty that I had sat on it for so long and not done anything. I also did not read your reply fully and missed the "I'm on it" at the end. I had some time over the holidays so I did it. I should have said something in the issue and I apologise.

**Comment by alexellis** [comment]
I'm glad that we have a PR in progress and one that's almost done. @alexandrevilain perhaps you'd like to help us test the PR from @adamjohnson01 once tested? @alexandrevilain there are other open issues available too on inlets/inletsctl and inlets-operator.

**Comment by alexandrevilain** [comment]
The most important thing is that the project is progressing well!
For sure, I'll try the EC2 provider as soon as it will be merged! 😃

**Comment by alexellis** [comment]
Merged and released: https://github.com/inlets/inletsctl/releases/tag/0.3.6

Thank you @adamjohnson01 :pray: 

@alexandrevilain please take a look :smile:

**Comment by alexandrevilain** [comment]
Hi @alexellis and @adamjohnson01 ! 

Just tested the `ec2` provisioner. I was explaining that port 80 or 443 weren't opened but I just saw: https://github.com/inlets/inletsctl/pull/26 

I'll try it another time after the PR is merged.

**Comment by alexandrevilain** [comment]
I've found another issue, the `--region` flag isn't supported for instance delete. `eu-west-1` is hardcoded. I can do the PR if you want.

**Comment by alexandrevilain** [comment]
Here is the PR: https://github.com/inlets/inletsctl/pull/27

**Comment by alexellis** [comment]
Thanks all, @adamjohnson01's PR is merged now. Would be great to get some additional testing
