### ISSUE TITLE
Support issue for Flux/k3d

### ISSUE THREAD

**Issue by colek42** [inlets/inlets-operator#19]
Getting connection refused errors
```
time="2019-10-22T23:38:19Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
time="2019-10-22T23:38:19Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
time="2019-10-22T23:38:24Z" level=info msg="Connecting to proxy" url="ws://178.128.168.110:8080/tunnel"
time="2019-10-22T23:38:24Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
time="2019-10-22T23:38:24Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
time="2019-10-22T23:38:29Z" level=info msg="Connecting to proxy" url="ws://178.128.168.110:8080/tunnel"
time="2019-10-22T23:38:29Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
time="2019-10-22T23:38:29Z" level=error msg="Failed to connect to proxy" error="dial tcp 178.128.168.110:8080: connect: connection refused"
```

Using flux, current manifest:  https://github.com/colek42/k3d-bootstrap/tree/fe0f92d4025d40bc924e820362e0127698b94682/releases

## Expected Behaviour
When the repo is bootstrapped I should see the default backend.

## Current Behaviour
This error is happening when when installing an ingress-nginx controller in a k3d environment.  The tunnel should connect and I should see a default backend. Hitting the ingress controller on the `NodePort` works as expected 

## Steps to Reproduce (for bugs)
https://github.com/colek42/k3d-bootstrap/tree/fe0f92d4025d40bc924e820362e0127698b94682/releases  (flux repo)

## Context
I am trying to get ingress working on bootstrap.

## Your Environment

* inlets version, find via `kubectl get deploy inlets-operator -o wide`
0.3.2

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
k3d

* Kubernetes version `kubectl version`:
1.14.4 k3s

* Operating System and version (e.g. Linux, Windows, MacOS):
linux-ubuntu 19

* Cloud provisioner: (DigitalOcean.com / Packet.com)
DO

**Comment by alexellis** [comment]
Hi, thanks for trying inlets.

Did an exit node get provisioned?

Did you see the IP get updated?

What are the logs of the operator?

Alex

**Comment by alexellis** [comment]
I can't see the sealedsecret for your `inlets-access-key` in the repo?

**Comment by colek42** [comment]
It was a bug in my bash script, I was using my default cluster rather than the k3d cluster.  Good thing my default cluster isn't prod!

**Comment by alexellis** [comment]
Glad you have it working thanks for letting me know.

**Comment by alexellis** [comment]
Btw, if you need user-support in the future, there's an #inlets channel on the OpenFaaS Slack https://slack.openfaas.io/
