### ISSUE TITLE
[Feature request] Multiplex a single exit-node

### ISSUE THREAD

**Issue by shawngmc** [inlets/inlets-operator#28]
Currently, inlets-operator creates one exit-node (DO Droplet, etc.) for each LoadBalancer created. This can add up quickly if a number of services are behind the load balancer.

Inlets offers the ability to set multiple upstreams. For example, from https://blog.alexellis.io/https-inlets-local-endpoints/:

```
inlets client \
 --remote wss://exit.domain.com \
 --upstream=gateway.domain.com=http://127.0.0.1:8080,prometheus.domain.com=http://127.0.0.1:9090
```

Will inlets-operator offer this capability as well?

## Expected Behaviour
When creating a 2nd load balancer, if a valid one exists, use Caddy + inlet upstreams to differentiate on the existing exit node

## Current Behaviour
A second exit-node is created on the external provider.

## Possible Solution
Use a forwarding setup similar to the one from the blog post, using Caddy to recognize a subdomain, etc.

## Steps to Reproduce (for bugs)
```
kubectl create secret generic inlets-access-key --from-literal inlets-access-key="DO_ACCESS_KEY_HERE"
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/crd.yaml
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/operator-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/operator.yaml
kubectl run nginx-1 --image=nginx --port=80 --restart=Always
kubectl run nginx-2 --image=nginx --port=80 --restart=Always
kubectl expose deployment nginx-1 --port=80 --type=LoadBalancer
kubectl expose deployment nginx-2 --port=80 --type=LoadBalancer
```

## Your Environment

* inlets version, find via `kubectl get deploy inlets-operator -o wide`

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop: Rancher

* Kubernetes version `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS): Linux CentOS 8

* Cloud provisioner: DigitalOcean.com

**Comment by alexellis** [comment]
Thanks for using the inlets-operator.

LBs from Cloud providers are around 15 USD +/-. Inlets is already 3x cheaper than that when using DigitalOcean (5USD per IP)

This feature is not in scope at present, I suspect it would be rather complicated and time-consuming and as inlets is provided for free at no cost, it's hard to justify right now.

If multiples of 5 USD are a concern. perhaps you could try out using inlets with your own YAML files using the samples from the main repo? https://github.com/inlets/inlets/blob/master/docs/kubernetes.md

**Comment by utsavanand2** [comment]
Or maybe use something like an nginx ingress controller? That way we can
have a single service hence a single instance ?
