### ISSUE TITLE
[Feature Request] Add provisioner for GCP Compute

### ISSUE THREAD

**Issue by rugwirobaker** [inlets/inlets-operator#30]
## Expected Behaviour
[Feature]Add provisioner for GCP Compute

## Current Behaviour
Exit nodes can be provisioned to DO/Packet

## Possible Solution
1. Explore the "provision" package - https://github.com/inlets/inlets-operator/tree/master/pkg/provision

2. Integrate the GCP SDK for Go

Example:  https://github.com/googleapis/google-api-go-client/blob/master/examples/compute.go

**Comment by alexellis** [comment]
This was actually done in #26 but @utsavanand2 accidentally overwrote his changes.

I would expect him to pick up the change again soon.

Thanks for requesting the feature, this is already on the backlog on the README under " Provision to GCP"

**Comment by rugwirobaker** [comment]
Great, I previoulsy wanted a civo provisioner but I guess it might not be possible as of now since they don't have a go sdk.

**Comment by alexellis** [comment]
No I already wrote the code for Civo and it's in inletsctl, it just needs integrating here. You can use it with inletsctl already.

**Comment by alexellis** [comment]
#32

**Comment by utsavanand2** [comment]
PR #33 Resolves this issue

**Comment by alexellis** [comment]
Thanks @utsavanand2
