### ISSUE TITLE
[Feature] Add Civo.com provisioner support

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#32]
## Expected Behaviour

Provisioning to instances on Civo.com in the UK - for 5 USD / mo / instance.

## Current Behaviour

Available in inletsctl at present, but not in the operator.

## Possible Solution

Move the Civo code written for inletsctl into the "provision" package in this project

Related: #31

**Comment by rugwirobaker** [comment]
Can I do this? Seems I don't even have to change the code.

**Comment by alexellis** [comment]
@rugwirobaker if you feel you can test it end to end, how long do you think it'll be until you have a PR up?

**Comment by rugwirobaker** [comment]
I'm a bit confused here the issue #31 says we have to move the provision package to inletsctl yet one states that we must bring it here(which I thought was the task). And seeing as the there is on provision package here whatsoever it means I would have test for all the providers right?

**Comment by alexellis** [comment]
It needs integrating here into the controller workflow. No worries, I'll do it when I next have time

**Comment by rugwirobaker** [comment]
I can do it over the weekend

**Comment by alexellis** [comment]
@rugwirobaker it's been about 4 weeks since you committed to do the work over the weekend, how did you get on? Is it ready? :nerd_face:

**Comment by alexellis** [comment]
cc @Waterdrips @utsavanand2 who may also want to pick this up?

**Comment by adamjohnson01** [comment]
@alexellis , I can do this.

**Comment by alexellis** [comment]
Thank you @adamjohnson01 :muscle:
