### ISSUE TITLE
deployment.yaml template needs project-id command line argument for packet provisioning

### ISSUE THREAD

**Issue by jessBlok** [inlets/inlets-operator#39]
The Helm deployment.yaml template is missing project-id for provisioning on packet.com

## Expected Behaviour
template should pass project-id to the inlets-operator container

## Current Behaviour
template is passing region twice instead of project-id

{{- if .Values.packetProjectId }}
        - "-region={{.Values.packetProjectId}}"
{{- end }}

## Possible Solution
replace region with project-id

## Context
Provisioning to packet.com with latest version of helm chart does not work since project-id is not passed.

## Your Environment
inlets/inlets-operator:0.5.4

**Comment by alexellis** [comment]
Thanks for raising the issue. I have a recollection of fixing this, but maybe I didn't.

Are you sending a PR, or do you want me to do that?

**Comment by alexellis** [comment]
Version `0.5.5` of the chart has been updated. 

I'm also testing a `k3sup app` for Istio here -> https://github.com/alexellis/k3sup/pull/141
