### ISSUE TITLE
Add Support for an Azure Container Instance Provisioner

### ISSUE THREAD

**Issue by juan-lee** [inlets/inlets-operator#4]
Add support for using an Azure Container Instance as a provisioner.

## Expected Behaviour
The behavior would be similar to the droplet provisioner except it would use a container instance resource on azure instead of a digital ocean droplet.

## Current Behaviour
Currently inlet servers are only supported on digital ocean and packet.

## Context
inlet provides a very nice way to expose services from a private cluster. It would be great if azure customers could leverage this functionality.

**Comment by alexellis** [comment]
Sounds good to me, I'd be happy to accept a PR for this @juan-lee 

What are the costs of the ACI per month? Could you add table to the README with an estimation?

For Packet it's the $0.07, for DigitalOcean it's 5 USD / mo.

Thank you!

Alex

**Comment by alexellis** [comment]
https://github.com/alexellis/inlets-operator/issues/8

**Comment by juan-lee** [comment]
@alexellis The cost for ACI is around $40/month. Azure's cheapest VM will also be around the same price. It's a far cry from $5/mo you get on digital ocean, but is a little better than $0.07/hr (~$51/mo) on packet.

I'll add a table to the README. Thanks!

**Comment by alexellis** [comment]
Thank you, hopefully folks with Azure credits and at MSFT will find it useful, despite the rather exorbitant cost.

**Comment by alexellis** [comment]
Is this still of interest @juan-lee ?

**Comment by alexellis** [comment]
Where are we with this @juan-lee @lachie83 ?

**Comment by juan-lee** [comment]
@alexellis I'm shooting to have a PR for you by EOW. Sorry for the delay.

**Comment by alexellis** [comment]
No problem. You'll need to PR to the inletsctl project which is vendored here.

**Comment by adam7** [comment]
@juan-lee Is there any reason you chose ACI to implement an azure server rather than a vm? A B1S vm would cost only cost around 8 dollars a month.
