### ISSUE TITLE
[Bug] EC2 provisioner does not open client port 

### ISSUE THREAD

**Issue by adamjohnson01** [inlets/inlets-operator#45]
The version of inletsctl used by the operator does not allow access to any client ports in the security group that gets created. A [PR](https://github.com/inlets/inletsctl/pull/26) that fixes this has now been merged.

## Expected Behaviour

 Connections to the Kubernetes service succeed.

## Current Behaviour

Access to the client port is being blocked so connections fail.

## Steps to Reproduce (for bugs)

1. Deploy an EC2 exit node with the operator
2. Create a loadbalancer service
3. Attempt to connect to the service using the exit node public IP

## Your Environment

* Operator 0.5.6
* kind v0.6.0 go1.13.4 darwin/amd64
* Kubernetes: v1.16.0
* Operating System: MacOS 10.15.1 (19B88)
* Cloud provisioner: AWS EC2

**Comment by alexellis** [comment]
@adamjohnson01 would you be able to take this please?

**Comment by adamjohnson01** [comment]
@alexellis, sure. Will do.

**Comment by alexellis** [comment]
@adamjohnson01 since we have a couple of projects, I wanted to check in - is this working now, or is work still needed? is inletsctl affected?
