### ISSUE TITLE
[Feature] Add Azure Virtual Machine provider

### ISSUE THREAD

**Issue by zechenbit** [inlets/inlets-operator#47]
## Expected Behaviour
Adding the --provider azure flag should provision a new virtual machine instance on Microsoft Azure.

## Current Behaviour
There is no Azure provider to provision VM on Azure currently. There is an open issue for adding Azure Container Instance as provider, but Azure Virtual Machine is not the scope of issue https://github.com/inlets/inlets-operator/issues/4.

## Possible Solution
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-vm-rest-api

**Comment by alexellis** [comment]
I’m fine with this. The PR should be to inletsctl and perhaps just called azure?

**Comment by zechenbit** [comment]
I have updated the provider from "azurevm" to "azure" in the issue description.

**Comment by alexellis** [comment]
Thank you for the PR 👍
