### ISSUE TITLE
The GCE exit node doesn't delete with `kubectl delete svc`

### ISSUE THREAD

**Issue by utsavanand2** [inlets/inlets-operator#50]
The GCE exit node doesn't delete with `kubectl delete svc`

## Expected Behaviour

Deleting the kubernetes service with a `kubectl delete svc <svc_name>` should delete the exit node on GCE with the service.

## Current Behaviour

The service gets deleted as expected but not the exit node
<img width="1275" alt="Screenshot 2020-02-10 at 7 24 58 PM" src="https://user-images.githubusercontent.com/25264581/74155978-72248980-4c3b-11ea-822f-7d65fb9a58a5.png">

## Possible Solution

PR is underway

## Steps to Reproduce (for bugs)

1. Follow the steps in the README for exit node on GCE 
2. Run nginx with a service exposing the deployment
3. Try deleting the service with `kubectl delete <svc_name>

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
0.6.2

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
minikube version: v1.2.0

* Cloud provisioner: (DigitalOcean.com / Packet.com / etc)
Google Cloud Platform

**Comment by utsavanand2** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thank you
