### ISSUE TITLE
Show columns for tunnel crd with "-o wide"

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#51]
Show columns for tunnel crd with "-o wide"

## Expected Behaviour

As per https://github.com/openfaas-incubator/ingress-operator/pull/23, we can show additional data when users run `kubectl get tunnels -o wide`

## Current Behaviour

Nothing is shown unless using `-o yaml`

## Possible Solution

Add the most interesting fields here, especially the status and IP address.

## Context

Thank you to Duffie @mauilion for this suggestion.

**Comment by alexellis** [comment]
@stefanprodan also does this with his Flagger project - https://github.com/weaveworks/flagger/blob/master/kustomize/base/flagger/crd.yaml#L58

**Comment by utsavanand2** [comment]
Derek assign: me
