### ISSUE TITLE
Error swallowed when provisioning with GCP and no projectID

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-operator#52]
The error is swallowed when provisioning with GCP and no projectID.

## Expected Behaviour

An error at the least in the logs, or a start-up error perhaps?

## Current Behaviour

There's no error or logs, but also no status or IP, this was found by found by Duffie @mauilion.

## Possible Solution

Reproduce the issue by misconfiguring without a project ID - (caused by https://github.com/alexellis/k3sup/issues/186) - then see the error and do what we can to fix it.

## Context

Confusing for new users outside of the usual flow of using Packet/DO.

**Comment by utsavanand2** [comment]
Derek assign: me
