### ISSUE TITLE
License argument should be "inletsProLicense" not "license" in chart README

### ISSUE THREAD

**Issue by hugomd** [inlets/inlets-operator#56]
The argument passed to helm here:

https://github.com/inlets/inlets-operator/blob/f01a5bc7e880643391a74aad8af2a89eeec182ee/chart/inlets-operator/README.md#L41-L46

Should be `inletsProLicense` not `license`.

## Context
I ran into an issue applying the license after copying this line, but worked it out pretty quickly as the value is different in `values.yaml`.

**Comment by alexellis** [comment]
Thanks for this. I suspect it's that way from the k3sup app, which I world recommend you try. K3sup wraps helm with strongly typed flags and validation, and installs to any k8s.

Will also fix this 👍

**Comment by hugomd** [comment]
I've fixed it locally, happy to push up a PR for it if you'd like

**Comment by utsavanand2** [comment]
Thank you @hugomd ! I've added the required changes in the latest PR #57 . Hope this helps!
