### ISSUE TITLE
[Feature request] Support provisioning to multiple regions for exit-servers

### ISSUE THREAD

**Issue by jahanson** [inlets/inlets-operator#63]
## Expected Behaviour

The operator should create the tunnel reliably without worrying what region is accepting new nodes.

## Current Behaviour

When specifying the region with digital ocean I can only specify one region. When the region is currently not accepting any new nodes it just fails until digital ocean re-enables the zone.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1548511/75401888-10b21b00-58c9-11ea-8db9-585ad8594ade.png">

![image](https://user-images.githubusercontent.com/1548511/75402030-64bcff80-58c9-11ea-84b4-169c4d0e63b3.png)

![image](https://user-images.githubusercontent.com/1548511/75402046-72728500-58c9-11ea-83ef-722c33659a9c.png)

## Possible Solution

specify a comma separated list
```-region=sfo1,sfo2```

## Steps to Reproduce (for bugs)

Go to Digital Ocean, add a new node and check to see what region is not currently accepting new nodes and specify that region in the configuration.

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
**inlets/inlets-operator:0.6.6**

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
**Rancher v2.3.2**

* Kubernetes version `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): **Ubuntu 18.04.4 LTS**

* Cloud provisioner: **DigitalOcean.com**

**Comment by alexellis** [comment]
/set title: [Feature request] Support provisioning to multiple regions for exit-servers

**Comment by alexellis** [comment]
Hi @jahanson 

Thanks for the suggestion. This isn't something we've encountered as of yet.

I noticed your operator version is very old, 0.9.2 is current and you should upgrade as soon as you can.

If you're using inlets for business purposes and confidential data/credentials then you [should purchase inlets PRO](https://inlets.dev/) so that your connections are encrypted. The OSS version is configured for testing only.

Please read more at [inlets tunnel capabilities](https://github.com/inlets/inlets-operator#inlets-tunnel-capabilities)
