### ISSUE TITLE
Update load balancer status

### ISSUE THREAD

**Issue by ameier38** [inlets/inlets-operator#70]
The `status.loadBalancer.ingress` is not updated after being assigned an external IP address.

## Expected Behaviour

After deploying a service of type `LoadBalancer` I expect that the `status.loadBalancer.ingress` will be updated with the IP address of the exit node.

## Current Behaviour

The current status is empty but the service was successfully assigned an external IP address.
```yaml
status:
loadBalancer: {}
```

## Possible Solution

[This line](https://github.com/inlets/inlets-operator/blob/master/controller.go#L867) is commented out which seems like it would fix the issue. Not sure if this is intentional.

## Steps to Reproduce (for bugs)

1. Deploy the inlets-operator as described in this repo
2. Deploy a service of type `LoadBalancer`
3. Wait for the service to be assigned an external IP address
4. Inspect the service `kubectl get svc <my service> -o yaml`
5. Observe that the `status.loadBalancer` is empty

## Context

First, awesome project. Was able to get the inlets working on private RPi cluster in no time. The only
issue I am having now is that when using Pulumi, there is a check to make sure a service of type `LoadBalancer` is successfully assigned an IP address by inspecting the `status.loadBalancer.ingress[0].ip`. Currently the inlets operator does not update this status so my deployment hangs (despite successfully creating an exit node and assigning an external IP address).
```
error: 2 errors occurred:
        * resource infrastructure/traefik was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'traefik' timed out waiting to be Ready
        * Service was not allocated an IP address; does your cloud provider support this?
```

## Your Environment

* inlets-operator version, find via `kubectl get deploy inlets-operator -o wide`
inlets/inlets-operator:0.7.0

* Kubernetes distribution i.e. minikube v0.29.0., KinD v0.5.1, Docker Desktop:
k3s on Raspberry Pi

* Kubernetes version `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:07:30Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm"} 
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

* Cloud provisioner: (DigitalOcean.com / Packet.com / etc)
Digital Ocean

**Comment by alexellis** [comment]
Hi Andrew,

I can't reproduce this?

Can you?

Alex

**Comment by skycoop** [comment]
I am also encountering this problem

My environment:
- Kubernetes (running using k3s on a Raspberry Pi 4 cluster)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-17T08:59:10Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+k3s1", GitCommit:"698e444a03fe3a705849fc8d9ad9e35f1dffe286", GitTreeState:"clean", BuildDate:"2020-05-07T00:18:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/arm"}
```
- inlets-operator version: v0.7.6
- Cloud provider GCP

Deployed inlets-operator using the helm chart with the following values
```yaml
provider: gce
projectID: homelab-277422
zone: us-central1-f
clientImage: inlets/inlets:2.7.0
```

When I get the YAML for a service using the LoadBalancer type, the `status.loadBalancer` field is empty
```
$ kubectl get svc --namespace kube-system traefik -o yaml
...
status:
  loadBalancer: {}
```

**Comment by skycoop** [comment]
Was just poking around the codebase to see if I could find what might be causing this not to work. Seems quite likely that this was broken when this block of code was commented out
https://github.com/inlets/inlets-operator/blob/2f3018ca05bf1a6c6532236c9ca89c14b65b688d/controller.go#L867-L869

**Comment by alexellis** [comment]
You are receiving absolutely no IP anywhere? That's really odd because I am and have used it over the last few days.

Can you show the full output?

Include get tunnels -o wide

**Comment by skycoop** [comment]
I am receiving an IP in the `spec.externalIPs` field of the service in question, but a ton of systems operate on the `status.LoadBalancer.Ingress` entries. Traefik uses this to set the external IP addresses of ingresses, which is then used by other tools like `external-dns` (which uses that IP address to create A records for the ingress hosts pointing to the inlets tunnel). 

This seems like the canonical method as GKE's and DigitalOcean's native LoadBalancer implementation both seem to use this behaviour
```yaml
# sample of GKE service yaml
status:
  loadBalancer:
    ingress:
    - ip: 10.20.101.101
```

**Comment by alexellis** [comment]
That was the original approach I took, but there was a reason why it was changed (which I cannot remember) - the git blame may explain it potentially, if you can take a look at the history.

So the service Ip is being updated correctly, it's just a case of integration with Ingress and the external-dns project that is affected?

Have you tested the change extensively?

**Comment by skycoop** [comment]
I did take a look at the history and I couldn't get a clear answer. I know the commented out code wouldn't work anymore since `Update` and `UpdateStatus` were split into separate methods, which was caused by the status field being handled by separate RBAC rules. 

As far as testing, I deployed the code from the PR to my cluster and it immediately propagated the external IP address all the way through to `external-dns` since I already had the Traefik chart configured with `kubernetes.ingressEndpoint.useDefaultPublishedService`

**Comment by alexellis** [comment]
We have this behaviour now, please correct me if I'm wrong.
