### ISSUE TITLE
[Q] Extend annotations

### ISSUE THREAD

**Issue by DarkBlaez** [inlets/inlets-operator#95]
Is it possible to extend the annocations to bypass inlets as the LoadBalancer, flipping this around to create an annocation that inlets-operator looks for to explicitly deploy. Like many, MetalLB is the default bare metal loadbalancer in a cluster for certain situations. Deploying the inlets-operator would result in two LB competing. MetalLB will always attempt to service type LoadBalancer. 

The inlets-operator is the ideal solution for routing external traffic in to a private cluster without having to go the route of site-to-site vpn and routing traffice. However, as I suspect inlets will interrogate all service types LB and go back and open up VMs for each.

Use case trying to be solved. IP addresses being assigned to internal services/sites, API gateway trying to be exposed to external internet traffic, inlets is ideal for this, whereas MetalLB is ideal fo assignin IP for internal use (private net)

DB

**Comment by ggriffin924** [comment]
I have the same issue, the local k8s and k3s clusters use metallb, and when you expose via type LoadBalancer they are provisioned with an address from Metallb.

**Comment by alexellis** [comment]
> Is it possible to extend the annocations to bypass inlets as the LoadBalancer, flipping this around to create an annotation that inlets-operator looks for to explicitly deploy. 

We do have that annotation it's called `dev.inlets.manage: false` and it's been in the project for some time now. You'll even see it mentioned on the README. Are we talking about the same thing here?

I guess my other question would be: does MetalLB not have the ability to be configured to via annotation to ignore LoadBalancers?

The idea of using annotations also depends on who creates the LoadBalancer. Most helm charts and tooling won't give you a chance to set any annotations before creating object, by which time it will be too late. 

I'd welcome input from both of you @DarkBlaez @ggriffin924 on the comments above

I'm going to close the issue assuming that it's not an issue and already covered, however do provide reproduction instructions if you feel this doesn't get covered by `dev.inlets.manage: false`

@ggriffin924 I'm not a MetalLB user so I'll need you to give step by step instructions here (don't miss any commands or config).

**Comment by alexellis** [comment]
/set title: Support request for multiple LoadBalancer controllers

**Comment by alexellis** [comment]
The other part of the docs you should see is: https://github.com/inlets/inlets-operator#annotations-and-ignoring-services

> You can also set the operator to ignore the services by default and only manage them when the annotation is true. dev.inlets.manage=true To do this, run the operator with the flag -annotated-only

**Comment by alexellis** [comment]
@DarkBlaez I'm confused why you opened another issue #101 with the same question. I've answered you here, we add the requested feature and it's documented.

Happy for you to tell me what I'm missing, but please, let's keep everything in one place.

**Comment by jsiebens** [comment]
There are some related issues reported in many different repositories, like:

https://github.com/kubernetes/kubernetes/issues/91306
https://github.com/metallb/metallb/issues/607
https://github.com/metallb/metallb/issues/685

**Comment by DarkBlaez** [comment]
I think the work around is to just not to deploy the operator. To be honest, Inlets is a special case, only needing to expose a service end-point externally. The inlets-kubernetes documentation is perfect and addresses the primary use case for Inlets. The operator notion that Inlets becomes the LB ends up extending beyonds this use case. There are situations where MetalLB (predominate for most who use a soft-LB) is the assignment of IP address from a pool and it blends well within an organization to assign and route traffic per IP to the cluster service (whatever that may be). Imagine Inlets operator deployed and the request for 10-30 services requiring LB. I cannot imagine spinning up of all those external VMs just to obtain and external IP for a service (db, ui, anything). 

I think nothing needs to be done here. I think those that use the Inlets operator will have to determine their use case. Inlets deployed in K8s routed to an api gateway is a perfect use case to route traffic externally to internal APIs, works perfect. The operator is just questionable based on use cases where existing soft-LBs are installed with existing running services. The work-around is to edit the manifest for those services and annotate to let Inlets know it needs to ignore. 

We can close this since there are specific work-arounds

Thanks
DB

**Comment by jsiebens** [comment]
@DarkBlaez to be clear, this feature is clearly documented in the readme: 

_You can also set the operator to ignore the services by default and only manage them when the annotation is true. dev.inlets.manage=true with the flag -annotated-only_

When running in this mode, you don't have to annotate your 10-30 services to avoid creating external VM, but rather explicitly annotate the service(s) you do want to expose with inlets.

**Comment by DarkBlaez** [comment]
And yet many have not discovered this option. I invite you to try the
operator out when you have Metal LB installed and review the behavior.

**Comment by alexellis** [comment]
@DarkBlaez I'm sorry that you didn't read the README and that you missed the notes about this feature. I've tried to make it clearer by adding bold headings about the two modes of the annotation. 

@blackjid added this almost a year ago and it was working for him at the time -> https://github.com/inlets/inlets-operator/pull/25

> I invite you to try the operator out when you have Metal LB installed and review the behavior.

I am sure that @jsiebens will take you up on that offer when he has time, but please answer us this: have you even tried it yet?

**Comment by DarkBlaez** [comment]
Yes I’ve tried it, any service that seeks to intercept type LB gets
invoked. Most soft-LB fail to consider competing intercepts. Intels
operator has done a good job on considering this so kudos. MetalLB and even
Ranchers lb-service has not.
