### ISSUE TITLE
Feature request: customise GCE plan

### ISSUE THREAD

**Issue by dirathea** [inlets/inlets-operator#96]
Currently Exit Node plan is hardcoded [here](https://github.com/inlets/inlets-operator/blob/50aea57bef66c934c3a76db2340714aa6f6eef26/controller.go#L531). I think it better to have some kind of customization on this plan.

## Expected Behaviour

`Plan` should be customizable with the default value if not provided.

## Current Behaviour

The operator use hardcoded value for plan (machine type).

## Possible Solution

Add additional run args or environment variable

## Context

I'm using this operator for help me extending my GCE credits for experiments. Going forward before I started using native GCE HTTP Load Balancer (that cost so much money than this approach), I want to scale the tunnel first.

**Comment by alexellis** [comment]
/set title: Feature request: customise GCE plan

**Comment by alexellis** [comment]
Hi @dirathea thanks for your suggestion.

For personal use I'd suggest that you fork the code, or set up a tunnel server using terraform and deploy a client YAML file to support that.

For context, what instance are you wanting to use, and what's the cost difference? Have you seen that there's a free tier on GCE?

Alex

**Comment by dirathea** [comment]
Hi @alexellis 
Yes, for my personal use I could fork this repo and build on my own.

For now, I will stick with the free f1-micro. But I might willing to spend a little more on this machine like `g1-micro`, or maybe `e1-small`, etc.

**Comment by utsavanand2** [comment]
@dirathea I'm assuming that you can get around by forking the repo and building it with the custom machine-type you want, I'm closing this issue for now. Please feel free to reopen the issue, if you fail to do so.
